export enum NET_EVENT {
    SOCKET_CONNECTING = "NET_EVENT.SOCKET_CONNECTING",
    SOCKET_CONNECTED = "NET_EVENT.SOCKET_CONNECTED",
    SOCKET_CONNFAIL = "NET_EVENT.SOCKET_CONNFAIL",
    SOCKET_CLOSED = "NET_EVENT.SOCKET_CLOSED",
    SOCKET_CLOSE = "NET_EVENT.SOCKET_CLOSE",
    SOCKET_MESSAGE = "NET_EVENT.SOCKET_MESSAGE",
    SOCKET_ERROR = "NET_EVENT.SOCKET_ERROR",

    SEND_MSG = "NET_EVENT.SEND_MSG",
    ON_RECV_DATA = "NET_EVENT.ON_RECV_DATA",
}

export enum SYS_EVENT {
    ON_BACKEND = "SYS_EVENT,ON_BACKEND",                       // 切后台
    ON_FRONT = "SYS_EVENT,ON_FRONT",
    NET_NETERROR = "SYS_EVENT.NET_NETERROR", 			          // 网络错误
    NETWORK_BAD = "SYS_EVENT.NETWORK_BAD",				          // 网络状况不好
    CHANGE_SCENE = "SYS_EVENT.CHANGE_SCENE",                // 场景切换
    CHANGE_SCENE_FINISH = "SYS_EVENT.CHANGE_SCENE_FINISH",  // 场景切换完成
    ENTER_MOD = "SYS_EVENT.ENTER_MOD",
    START_RECONNECT = "SYS_EVENT.START_RECONNECT",			    // 开始重连
    RECONNECT_SUCCESS = "SYS_EVENT.RECONNECT_SUCCESS",		  // 重连成功
    RECOVER_ROOMDATA = "SYS_EVENT.RECOVER_ROOMDATA",		    // 重连后 恢复房间数据 
    RESTART_GAME = "SYS_EVENT.RESTART_GAME",               // 桌面游戏一键重启
    LOADGAME_PROGRESS = "SYS_EVENT.LOADGAME_PROGRESS",     // 游戏加载进度
    LOADGAME_FINISH = "SYS_EVENT.LOADGAME_FINISH",			    // 游戏加载完成
    RECHARGE_SUCCEEDED = "SYS_EVENT.RECHARGE_SUCCEEDED",    // 充值成功
    ERROR_CODE = "SYS_EVENT.ERROR_CODE",                                // 系统错误
}
















export enum GAME_EVENT {
    TOAST = "GAME_EVENT.TOAST",
    ALERT = "GAME_EVENT.ALERT",

    PLAYER_SIT_DOWN = "GAME_EVENT.PLAYER_SIT_DOWN",
    PLAYER_STAND_UP = "GAME_EVENT.PLAYER_STAND_UP",
    PLAYER_OPREATE = "GAME_EVENT.PLAYER_OPREATE",
    ADD_ONE_ROUND = "GAME_EVENT.ADD_ONE_ROUND",
    TURN_ON = "GAME_EVENT.TURN_ON",
    SHOW_CARDTYPE = "GAME_EVENT.SHOW_CARDTYPE",
    UPDATE_WEALTH = "GAME_EVENT.UPDATE_WEALTH",
    UPDATE_BET = "GAME_EVENT.UPDATE_BET",
    DEAL_HANDCARDS = "GAME_EVENT.DEAL_HANDCARDS",
    SHOW_HANDCARDS = "GAME_EVENT.SHOW_HANDCARDS",
    SET_CARDTYPE = "GAME_EVENT.SET_CARDTYPE",
    SET_TRUSTEESHIP = "GAME_EVENT.SET_TRUSTEESHIP",

    CLICK_SPACE = "GAME_EVENT.CLICK_SPACE",
    ERROR_TIPS = "GAME_EVENT.ERROR_TIPS",
    LOGIN_SUCCEED = "GAME_EVENT.LOGIN_SUCCEED",
    SHOW_SAFE_PWD = "GAME_EVENT.SHOW_SAFE_PWD",
    SELECTED_COUTRY = "GAME_EVENT.SELECTED_COUTRY",
    SHOW_HONOR = "GAME_EVENT.SHOW_HONOR",
    SHOW_GODSYSTEM = "GAME_EVENT.SHOW_GODSYSTEM",
    SHOW_RECORDS_DETAIL = "GAME_EVENT.SHOW_RECORDS_DETAIL",
    REFRESH_USER_DATA = "GAME_EVENT.REFRESH_USER_DATA",
    REFRESH_USER_ADDRESS_INFO = "GAME_EVENT.REFRESH_USER_ADDRESS_INFO",
    LOG_OFF_ACCOUNT_MESSAGE = "GAME_EVENT.LOG_OFF_ACCOUNT_MESSAGE",
    SEND_QUEST_MESSAGE = "GAME_EVENT.SEND_QUEST_MESSAGE",


    ON_ENTER_TABLE = "GAME_EVENT.ON_ENTER_TABLE",
    SEND_SET_SERPWD_MESSAGE = "GAME_EVENT.SEND_SET_SERPWD_MESSAGE",

    ON_CHANGE_GAME_STATE = "GAME_EVENT.ON_CHANGE_GAME_STATE",
    ON_SET_GAME_STATE = "GAME_EVENT.ON_SET_GAME_STATE",
    ON_GET_MESSAGE_LIST = "GAME_EVENT.ON_GET_MESSAGE_LIST",
    ON_GET_BRIEF_MESSAGE = "GAME_EVENT.ON_GET_BRIEF_MESSAGE",
    ON_GET_SHOUCANG_MESSAGE = "GAME_EVENT.ON_GET_SHOUCANG_MESSAGE",
    ON_GET_HONOR_MESSAGE = "GAME_EVENT.ON_GET_HONOR_MESSAGE",
    ON_GET_HONOR_USER_MESSAGE = "GAME_EVENT.ON_GET_HONOR_USER_MESSAGE",
    ON_GET_CHEAT_QUERY_MESSAGE = "GAME_EVENT.ON_GET_CHEAT_QUERY_MESSAGE",
    ON_GET_CHEAT_QUERY_GAME_MESSAGE = "GAME_EVENT.ON_GET_CHEAT_QUERY_GAME_MESSAGE",

    ON_GET_PRODUCT_LIST_MESSAGE = "GAME_EVENT.ON_GET_PRODUCT_LIST_MESSAGE",
    ON_CREATE_ORDER_MESSAGE = "GAME_EVENT.ON_CREATE_ORDER_MESSAGE",
    ON_ORDER_LIST_QUERY_MESSAGE = "GAME_EVENT.ON_ORDER_LIST_QUERY_MESSAGE",

    ON_ROOM_LIST_MESSAGE = "GAME_EVENT.ON_ROOM_LIST_MESSAGE",

    ON_GAME_RECORD_INFO_QUERY = "GAME_EVENT.ON_GAME_RECORD_INFO_QUERY",

    ON_AUTH_SW_MESSAGE = "GAME_EVENT.ON_AUTH_SW_MESSAGE",

    ON_SET_SW_MESSAGE = "GAME_EVENT.ON_SET_SW_MESSAGE",

    ON_REQUEST_NEXT_PAGE = "GAME_EVENT.ON_REQUEST_NEXT_PAGE",

    ON_GET_CARDBAG_LIST_MESSAGE = "GAME_EVENT.ON_GET_CARDBAG_LIST_MESSAGE",

    ON_USER_INIT_FACE_VERIFY_MESSAGE = "GAME_EVENT.ON_USER_INIT_FACE_VERIFY_MESSAGE",

    ON_USER_DESCRIBE_FACE_MESSAGE = "GAME_EVENT.ON_USER_DESCRIBE_FACE_MESSAGE",


    UPDATE_SIGNUP_STATE = "GAME_EVENT.UPDATE_SIGNUP_STATE",


    ON_GAME_SCENE_TABLE_UPDATE = "GAME_EVENT.ON_GAME_SCENE_TABLE_UPDATE",

    ON_GAME_TABLE_INFO = "GAME_EVENT.ON_GAME_TABLE_INFO",

    ON_GAME_RECORD_INFO = "GAME_EVENT.ON_GAME_RECORD_INFO",

    ON_GAME_RECORD_COLLECT_INFO = "GAME_EVENT.ON_GAME_RECORD_COLLECT_INFO",

    ON_GAME_USER_LIST_INFO_QUERY = "GAME_EVENT.ON_GAME_USER_LIST_INFO_QUERY",

    ON_RECV_PROP = "ON_RECV_PROP",

    ON_GAME_BEGIN_DOWN_NUMBER = "ON_GAME_BEGIN_DOWN_NUMBER",

    ON_GAME_SEARCH_MY_DATA = "ON_GAME_SEARCH_MY_DATA",

    ON_CONTROL_MAIN_MASK = "ON_CONTROL_MAIN_MASK",

    ON_CHANGE_MAIN_TAP = "ON_CHANGE_MAIN_TAP",
    ON_RECEIVE_ORDER_STATE_QUERY = "ON_RECEIVE_ORDER_STATE_QUERY",
    ON_GAME_MY_BEIZHU_DATA = "ON_GAME_MY_BEIZHU_DATA",
    ON_GAME_MY_BEIZHU_UPDATE_DATA = "ON_GAME_MY_BEIZHU_UPDATE_DATA"
}

